/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cookies: typeof import('./src/components/Cookies.vue')['default']
    CurltoRquests: typeof import('./src/components/CurltoRquests.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Headers: typeof import('./src/components/Headers.vue')['default']
    Ocr: typeof import('./src/components/Ocr.vue')['default']
    PwdDecrypt: typeof import('./src/components/PwdDecrypt.vue')['default']
    Sign: typeof import('./src/components/Sign.vue')['default']
    Sms: typeof import('./src/components/Sms.vue')['default']
    Taskid: typeof import('./src/components/Taskid.vue')['default']
    Translation: typeof import('./src/components/Translation.vue')['default']
  }
}
